/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ghost-empty.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function EmptyObject(props) {
  const { nodes } = useGLTF('/Ghost-empty.glb')
  return (
    <group {...props} dispose={null}>

      {/* crypt */}
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube.geometry} visible={false} position={[0, 3, -10]} scale={[2.5, 2.5, 3.25]} />
      </RigidBody>

      {/* trees */}
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube001.geometry} visible={false} position={[-8.074, 0.7, -13.078]} scale={[0.247, 0.75, 0.293]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube002.geometry} visible={false} position={[-7.969, 0.7, -10.952]} scale={[0.186, 0.75, 0.221]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube003.geometry} visible={false} position={[-11.684, 0.7, -12.192]} scale={[0.271, 0.75, 0.32]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube004.geometry} visible={false} position={[-11.822, 0.7, -8.674]} scale={[0.271, 0.75, 0.32]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube005.geometry} visible={false} position={[-9.492, 0.7, -9.108]} scale={[0.182, 0.75, 0.216]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube006.geometry} visible={false} position={[-6.002, 0.7, -9.969]} scale={[0.469, 0.75, 0.555]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube007.geometry} visible={false} position={[6.038, 0.7, -10.016]} scale={[0.379, 0.75, 0.449]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube008.geometry} visible={false} position={[5.133, 0.7, -13.976]} scale={[0.304, 0.75, 0.36]} />
      </RigidBody>

      {/* gate wall */}
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube009.geometry} visible={false} position={[-3.794, 1.178, -15.983]} scale={[2.143, 1.291, 0.15]} />
      </RigidBody>

      {/* fence walls */}
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube010.geometry} visible={false} position={[-5.175, 1.178, 3.969]} scale={[4.63, 1.291, 0.15]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube011.geometry} visible={false} position={[5.768, 1.178, 3.996]} scale={[3.818, 1.291, 0.15]} />
      </RigidBody>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube012.geometry} visible={false} position={[-9.949, 1.178, -2.145]} rotation={[0, -Math.PI / 2, 0]} scale={[5.687, 1.291, 0.15]} />
      </RigidBody>

      {/* ground */}
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube013.geometry} visible={false} position={[0, -0.327, -2.173]} scale={[14.312, 0.253, 16.159]} />
      </RigidBody>

    </group>
  )
}

useGLTF.preload('/Ghost-empty.glb')