/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GHOST-compressed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/GHOST-compressed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arch.geometry} material={materials.HalloweenBits} position={[0, 2.207, -16]} scale={2.207} />
      <group position={[0, 0, 4]} scale={100}>
        <mesh geometry={nodes.arch_gate_left.geometry} material={materials.HalloweenBits} position={[0.009, 0.015, 0.004]} rotation={[0, 0.611, 0]} scale={0.015} />
        <mesh geometry={nodes.arch_gate_right.geometry} material={materials.HalloweenBits} position={[-0.008, 0.015, 0]} scale={0.015} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.HalloweenBits} position={[0, 0.022, 0]} scale={0.022} />
      </group>
      <mesh geometry={nodes.tree_pine_orange_medium.geometry} material={materials.HalloweenBits} position={[-11.812, 2.456, -8.494]} scale={2.936} />
      <mesh geometry={nodes.tree_pine_yellow_large.geometry} material={materials.HalloweenBits} position={[5.017, 3.183, -13.999]} scale={3.738} />
      <mesh geometry={nodes.tree_pine_orange_small.geometry} material={materials.HalloweenBits} position={[-9.484, 1.626, -9.145]} scale={2.021} />
      <mesh geometry={nodes.tree_pine_yellow_small.geometry} material={materials.HalloweenBits} position={[-12.984, 1.626, -3.045]} scale={2.021} />
      <mesh geometry={nodes.tree_pine_yellow_small001.geometry} material={materials.HalloweenBits} position={[12.016, 1.626, -2.045]} scale={2.021} />
      <mesh geometry={nodes.tree_pine_yellow_medium.geometry} material={materials.HalloweenBits} position={[-8.012, 2.456, -12.794]} scale={2.936} />
      <mesh geometry={nodes.tree_pine_orange_large.geometry} material={materials.HalloweenBits} position={[-11.783, 3.183, -12.199]} scale={3.738} />
      <mesh geometry={nodes.bench.geometry} material={materials.HalloweenBits} position={[11, 0.25, 5]} rotation={[0, -1.396, 0]} />
      <mesh geometry={nodes.bench001.geometry} material={materials.HalloweenBits} position={[-4, 0.25, -2]} rotation={[0, -1.396, 0]} />
      <mesh geometry={nodes.bench002.geometry} material={materials.HalloweenBits} position={[-6, 0.25, -0.3]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.bench_decorated.geometry} material={materials.HalloweenBits} position={[6, 0.839, -0.995]} />
      <mesh geometry={nodes.bone_A.geometry} material={materials.HalloweenBits} position={[9.3, 0, 3.4]} rotation={[0, Math.PI / 4, 0]} scale={0.353} />
      <mesh geometry={nodes.bone_C.geometry} material={materials.HalloweenBits} position={[9.4, 0, 5.8]} rotation={[0, Math.PI / 9, 0]} scale={0.553} />
      <mesh geometry={nodes.bone_B.geometry} material={materials.HalloweenBits} position={[11.306, 0, -0.7]} scale={0.303} />
      <mesh geometry={nodes.candle_thin.geometry} material={materials.HalloweenBits} position={[-6.1, 0.393, -1.703]} scale={0.393} />
      <mesh geometry={nodes.candle_melted.geometry} material={materials.HalloweenBits} position={[-7.2, 0.316, -1.205]} scale={0.316} />
      <mesh geometry={nodes.candle.geometry} material={materials.HalloweenBits} position={[-6, 0.393, -2.305]} scale={0.393} />
      <mesh geometry={nodes.candle_triple.geometry} material={materials.HalloweenBits} position={[-6.025, 0.393, -1.968]} scale={0.393} />
      <group position={[1, 0, -5.9]} scale={100}>
        <mesh geometry={nodes.path_A_1.geometry} material={materials.HalloweenBits} position={[-0.01, 0.001, 0.01]} scale={0.02} />
        <mesh geometry={nodes.path_A_2.geometry} material={materials.HalloweenBits} position={[-0.01, 0.001, 0.01]} scale={0.019} />
      </group>
      <mesh geometry={nodes.path_A002.geometry} material={materials.HalloweenBits} position={[-0.997, 0.05, 1.014]} rotation={[0, Math.PI / 2, 0]} scale={0.952} />
      <group position={[-11, 0, 8]} scale={100}>
        <mesh geometry={nodes.coffin_lid.geometry} material={materials.HalloweenBits} position={[-0.005, 0.01, 0.001]} rotation={[0, 0.461, 0]} scale={0.015} />
        <mesh geometry={nodes.mesh_22.geometry} material={materials.HalloweenBits} position={[0, 0.004, 0]} scale={0.015} />
      </group>
      <mesh geometry={nodes.coffin_decorated.geometry} material={materials.HalloweenBits} position={[9, 0.451, -7]} scale={1.5} />
      <mesh geometry={nodes.crypt.geometry} material={materials.HalloweenBits} position={[0, 4, -10]} scale={4} />
      <mesh geometry={nodes.grave_A_destroyed.geometry} material={materials.HalloweenBits} position={[-6.361, 1.053, -6.268]} scale={1.053} />
      <mesh geometry={nodes.tree_dead_large.geometry} material={materials.HalloweenBits} position={[-8.175, 2.261, 1.993]} rotation={[0, 0.175, 0]} scale={2.533} />
      <mesh geometry={nodes.tree_dead_large001.geometry} material={materials.HalloweenBits} position={[-8.129, 2.261, -10.881]} rotation={[0, 0.96, 0]} scale={2.533} />
      <mesh geometry={nodes.tree_dead_large002.geometry} material={materials.HalloweenBits} position={[3.919, 2.261, -7.844]} rotation={[0, 1.309, 0]} scale={2.533} />
      <mesh geometry={nodes.tree_dead_medium.geometry} material={materials.HalloweenBits} position={[7.419, 1.794, -5]} scale={2.094} />
      <group position={[-8, 0, 4]} scale={100}>
        <mesh geometry={nodes.floor_dirt_1.geometry} material={materials.HalloweenBits} position={[0.08, -0.002, -0.06]} scale={0.16} />
        <mesh geometry={nodes.floor_dirt_2.geometry} material={materials.HalloweenBits} position={[0, -0.007, 0.04]} scale={0.02} />
        <mesh geometry={nodes.floor_dirt_3.geometry} material={materials.HalloweenBits} position={[0.08, -0.002, -0.06]} scale={0.14} />
      </group>
      <mesh geometry={nodes.fence007.geometry} material={materials.HalloweenBits} position={[-0.125, 1.1, -1.875]} rotation={[0, Math.PI / 2, 0]} scale={10.125} />
      <mesh geometry={nodes.fence_broken001.geometry} material={materials.HalloweenBits} position={[10, 1.1, -3]} rotation={[0, Math.PI / 2, 0]} scale={2} />
      <mesh geometry={nodes.fence_broken002.geometry} material={materials.HalloweenBits} position={[-8, 1.1, 4]} rotation={[-Math.PI, 0, -Math.PI]} scale={2} />
      <group position={[-4, 0, -16]} scale={100}>
        {nodes.mesh_34_instance_1 && (
          <mesh geometry={nodes.mesh_34_instance_1.geometry} material={materials.HalloweenBits} position={[0, 0.011, 0]} scale={0.02} />
        )}
        <mesh geometry={nodes.fence_gate_left.geometry} material={materials.HalloweenBits} position={[0.008, 0.015, 0]} scale={0.015} />
        <mesh geometry={nodes.fence_gate_right.geometry} material={materials.HalloweenBits} position={[-0.008, 0.015, 0]} scale={0.015} />
      </group>
      <mesh geometry={nodes.fence_gate001.geometry} material={materials.HalloweenBits} position={[9.8, 1.1, 1.7]} rotation={[0, Math.PI / 2, 0]} scale={2} />
      <mesh geometry={nodes.grave_A.geometry} material={materials.HalloweenBits} position={[6, 1.065, -2]} scale={1.065} />
      <mesh geometry={nodes.gravemarker_A.geometry} material={materials.HalloweenBits} position={[7.969, 0.598, 4.972]} scale={0.598} />
      <mesh geometry={nodes.gravemarker_B.geometry} material={materials.HalloweenBits} position={[7.321, 0.59, 5.768]} rotation={[0, 0.175, 0]} scale={0.59} />
      <mesh geometry={nodes.gravestone.geometry} material={materials.HalloweenBits} position={[4.1, 0.8, -6.7]} rotation={[0, 0.436, 0]} scale={0.8} />
      <mesh geometry={nodes.grave_B.geometry} material={materials.HalloweenBits} position={[-5.4, 1.1, -12.9]} rotation={[0, -Math.PI / 2, 0]} scale={1.1} />
      <mesh geometry={nodes.lantern_hanging.geometry} material={materials.HalloweenBits} position={[0, -0.604, 4]} scale={0.704} />
      <mesh geometry={nodes.pumpkin_yellow_jackolantern.geometry} material={materials.HalloweenBits} position={[6, 0.646, 5]} scale={0.75} />
      <mesh geometry={nodes.lantern_standing.geometry} material={materials.HalloweenBits} position={[1.3, 0.463, -0.6]} scale={0.463} />
      <group position={[1.1, 0, 1.9]} rotation={[0, Math.PI / 2, 0]} scale={100}>
        <mesh geometry={nodes.path_B003_2.geometry} material={materials.HalloweenBits} position={[-0.02, 0.001, -0.02]} scale={0.01} />
        <mesh geometry={nodes.path_B003_1.geometry} material={materials.HalloweenBits} position={[-0.01, 0, -0.01]} scale={0.019} />
      </group>
      <group position={[-0.9, 0, -2]} rotation={[-Math.PI, 0, -Math.PI]} scale={100}>
        <mesh geometry={nodes.path_B005_2.geometry} material={materials.HalloweenBits} position={[-0.02, 0.001, -0.02]} scale={0.01} />
        <mesh geometry={nodes.path_B005_1.geometry} material={materials.HalloweenBits} position={[-0.01, 0, -0.01]} scale={0.019} />
      </group>
      <mesh geometry={nodes.path_B001.geometry} material={materials.HalloweenBits} position={[-2.99, 0.05, -4.102]} scale={0.943} />
      <mesh geometry={nodes.path_B002.geometry} material={materials.HalloweenBits} position={[-0.99, 0.05, -1.002]} scale={0.943} />
      <mesh geometry={nodes.path_B004.geometry} material={materials.HalloweenBits} position={[0.998, 0.05, 0.99]} rotation={[0, Math.PI / 2, 0]} scale={0.943} />
      <mesh geometry={nodes.path_B006.geometry} material={materials.HalloweenBits} position={[1.11, 0.05, 5.898]} scale={0.943} />
      <mesh geometry={nodes.path_B007.geometry} material={materials.HalloweenBits} position={[-0.89, 0.05, 5.898]} scale={0.943} />
      <mesh geometry={nodes.path_B008.geometry} material={materials.HalloweenBits} position={[-0.99, 0.05, 7.798]} scale={0.943} />
      <mesh geometry={nodes.path_B009.geometry} material={materials.HalloweenBits} position={[-5.002, 0.05, -4.11]} rotation={[0, Math.PI / 2, 0]} scale={0.943} />
      <mesh geometry={nodes.path_C.geometry} material={materials.HalloweenBits} position={[0.912, 0.05, 7.903]} scale={0.928} />
      <mesh geometry={nodes.path_C001.geometry} material={materials.HalloweenBits} position={[-6.912, 0.05, -4.103]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.928} />
      <mesh geometry={nodes.path_C002.geometry} material={materials.HalloweenBits} position={[3.012, 0.05, -3.997]} scale={0.928} />
      <mesh geometry={nodes.plaque.geometry} material={materials.HalloweenBits} position={[6, 0.2, -6]} />
      <mesh geometry={nodes.plaque001.geometry} material={materials.HalloweenBits} position={[-6, 0.2, -2]} />
      <mesh geometry={nodes.plaque_candles.geometry} material={materials.HalloweenBits} position={[0, 0.566, -12]} />
      <mesh geometry={nodes.post.geometry} material={materials.HalloweenBits} position={[3.004, 1.65, 3.567]} scale={1.65} />
      <group position={[-4.2, 0, 6.3]} scale={100}>
        <mesh geometry={nodes.post_lantern_lantern.geometry} material={materials.HalloweenBits} position={[0, 0.024, 0.01]} scale={0.007} />
        <mesh geometry={nodes.mesh_52.geometry} material={materials.HalloweenBits} position={[0, 0.016, 0.006]} scale={0.016} />
      </group>
      <group position={[-12, 0, 4]} scale={100}>
        <mesh geometry={nodes.post_skull_skull.geometry} material={materials.HalloweenBits} position={[0, 0.024, 0.009]} scale={0.007} />
        <mesh geometry={nodes.mesh_54.geometry} material={materials.HalloweenBits} position={[0, 0.016, 0.006]} scale={0.016} />
      </group>
      <mesh geometry={nodes.pumpkin_orange.geometry} material={materials.HalloweenBits} position={[4.8, 0.347, 5.4]} rotation={[0, -0.611, 0]} scale={0.501} />
      <mesh geometry={nodes.pumpkin_orange_jackolantern.geometry} material={materials.HalloweenBits} position={[-4, 0.646, 5]} scale={0.75} />
      <mesh geometry={nodes.ribcage.geometry} material={materials.HalloweenBits} position={[-3.9, 0.288, -12.948]} scale={0.429} />
      <mesh geometry={nodes.path_D.geometry} material={materials.HalloweenBits} position={[-1.089, 0.05, 9.829]} scale={0.853} />
      <mesh geometry={nodes.path_D001.geometry} material={materials.HalloweenBits} position={[-8.689, 0.05, -4.171]} scale={0.853} />
      <mesh geometry={nodes.path_D002.geometry} material={materials.HalloweenBits} position={[4.988, 0.05, -4.044]} rotation={[-Math.PI, 1.309, -Math.PI]} scale={0.853} />
      <mesh geometry={nodes.shrine.geometry} material={materials.HalloweenBits} position={[6, 1.2, -10]} scale={1.2} />
      <mesh geometry={nodes.shrine_candles.geometry} material={materials.HalloweenBits} position={[-6, 0.895, -10]} scale={0.895} />
      <mesh geometry={nodes.skull.geometry} material={materials.HalloweenBits} position={[-9.603, 0.467, 6.196]} rotation={[0, 0.698, 0]} scale={0.459} />
      <mesh geometry={nodes.tree_dead_small.geometry} material={materials.HalloweenBits} position={[9.573, 1.197, -15.092]} rotation={[-Math.PI, -0.698, -Math.PI]} scale={1.493} />
      <mesh geometry={nodes.pumpkin_yellow.geometry} material={materials.HalloweenBits} position={[-5.2, 0.347, 4.7]} rotation={[0, -Math.PI / 9, 0]} scale={0.501} />
      <mesh geometry={nodes.pumpkin_orange_small.geometry} material={materials.HalloweenBits} position={[-9.5, 0.272, -6.7]} scale={0.3} />
      <mesh geometry={nodes.pumpkin_orange_small001.geometry} material={materials.HalloweenBits} position={[-4.8, 0.272, 5.6]} rotation={[0, 0.436, 0]} scale={0.3} />
      <mesh geometry={nodes.tree_dead_large_decorated.geometry} material={materials.HalloweenBits} position={[7.829, 2.436, 2.952]} scale={2.709} />
      <mesh geometry={nodes.pumpkin_yellow_small.geometry} material={materials.HalloweenBits} position={[5.4, 0.272, 5.8]} scale={0.3} />
    </group>
  )
}

useGLTF.preload('/GHOST-compressed.glb')
