/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GhostUser.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GhostUser(props) {
  const { nodes, materials } = useGLTF('/GhostUser.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bone_C.geometry} material={materials['HalloweenBits.011']} rotation={[-Math.PI, 0.877, -2.205]} scale={0.553} />
    </group>
  )
}

useGLTF.preload('/GhostUser.glb')
