/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/GhostPlayer.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GhostPlayer(props) {
  const { nodes, materials } = useGLTF('/GhostPlayer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.03, 0]} scale={84.931}>
        <mesh geometry={nodes.skull_1.geometry} material={materials['HalloweenBits.056']} position={[0, 0.005, 0]} scale={0.005} />
        <mesh geometry={nodes.skull_2.geometry} material={materials['HalloweenBits.056']} position={[0, -0.004, 0]} scale={0.004} />
      </group>
    </group>
  )
}

useGLTF.preload('/GhostPlayer.glb')
